### ISSUE TITLE
What is the minimum gas price (GWEI) and what would be the minimum gas limit that I should set for my withdrawal to be successful?

### ISSUE THREAD

**Issue by piero6758** [Steemhunt/neverlose.money-contract#20]
![NEVER](https://user-images.githubusercontent.com/76655577/117934996-3e6a6080-b2d1-11eb-8cfd-22c053cdb21a.jpg)
Hello I have 0.02 WETH unlocked and I want to withdraw it.

The problem is that the commission is the incredible sum of $ 243.43.

I know that I can customize the gas to make the economic commission, but I don't know what is recommended for the transaction to go well.

Now I ask you the following questions:

What is the minimum gas price (GWEI) that I should place on your recommendation? And what would be the minimum gas limit that you should put in your recommendation?

Your project has seemed great to me from the beginning, I want to continue in this project but I need your help and I know that I will get it.

I am looking forward to your response!

**Comment by sebayaki** [comment]
You can set the minimum gas price as the value you can check here:
https://www.gasnow.org/

Take the "Slow" number, if you go lower than that, your transaction could hang more than few days.
Also gas cost has become very expensive in recent few days, so I would recommend wait for few more days until it goes down to lower level (40-50gwei is good range these days)

You can find historical gas price data on the website as well.

![image](https://user-images.githubusercontent.com/1332279/117995443-49c69600-b37c-11eb-932b-6c1cd73c269b.png)

You don't need to change the "Gas limit", because left over will be refunded at the end of the transaction anyway.
